### ISSUE TITLE
Odkaz pro Komercni banku

### ISSUE THREAD

**Issue by jirkastejskal** [JirkaChadima/cz-banking-psd2#4]
Odkaz nikam nevede, ale funguje jim https://microsite.kb.cz/cs/open-banking/kb-api jako rozcestnik.

**Comment by JirkaChadima** [comment]
Uz se tehle oblasti nevenuju, takze nemam ambici drzet repozitar aktualni. Naopak ho zaarchivuju, at to nemate dalsi lidi
